services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  tunnel-server:
    build: .
    environment:
      - REDIS_URL=redis://redis
    ports:
      - "7000:7000"
    deploy:
      replicas: 3

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
